### ISSUE TITLE
Wire up reset cache button on data point UI

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#372] opened 2021-02-02 00:11 UTC
This button should make a POST to `runtime-manager/reset-cache`

![image](https://user-images.githubusercontent.com/3905204/106534066-5abb5d80-6497-11eb-8108-b6a8ba9a20c2.png)

**Comment by pierpuccini** [comment] 2021-02-02 20:21
Duplicate of #371

**Closed by pierpuccini** 2021-02-02 20:21 UTC
