### ISSUE TITLE
Dashboard Designer - Validation messages not shown

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#54] opened 2017-03-30 22:14 UTC
After implementing the code to reject saves for a page when the User does not have edit permission the Rejected response is not indicated anywhere on the page and the user gets no feedback that the save failed.

To reproduce just try to create a new page as a user without edit-pages permission.

**Comment by jazdw** [comment] 2017-04-03 19:38
Closing as duplicate of #42

**Closed by jazdw** 2017-04-03 19:38 UTC
Labels: Bug, Enhancement
